import type { CandidateProfile, ParsedJD } from "./types";
import { parseJD } from "./jd";

export const DEFAULT_SAMPLE_JD = `Senior Backend Engineer — GenAI Platform

We are hiring a Senior Backend Engineer to build backend services for our GenAI platform. The ideal candidate has 5+ years of software engineering experience, strong Python, FastAPI, PostgreSQL, Docker, cloud experience, and experience with LLM APIs. Experience with RAG pipelines, vector databases, and distributed systems is preferred. Location: Remote India.

Responsibilities:
- Design and operate scalable backend services for AI product workflows.
- Build API layers, async jobs, observability, and integrations with LLM providers.
- Improve reliability, latency, and developer experience across the platform.
- Partner with product, data, and ML teams to ship safe GenAI features.

Preferred:
- Retrieval augmented generation, vector databases, distributed systems, Kubernetes, TypeScript.
- Experience owning production systems and mentoring engineers.`;

export const sampleParsedJD: ParsedJD = parseJD(DEFAULT_SAMPLE_JD);

export const demoCandidates: CandidateProfile[] = [
  {
    id: "demo-aanya-menon",
    name: "Aanya Menon",
    email: "aanya.menon@example.com",
    phone: "+91 98765 10101",
    location: "Bengaluru, India",
    currentTitle: "Senior Backend Engineer, GenAI Platform",
    currentCompany: "NimbleStack AI",
    yearsExperience: 8,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "Kubernetes", "AWS", "LLM APIs", "RAG", "Vector Databases", "Distributed Systems"],
    projects: ["Built a multi-tenant RAG orchestration service using pgvector and FastAPI", "Led LLM gateway reliability work for 12 product teams"],
    summary: "Backend platform engineer with production GenAI systems, API design, and strong cloud operations experience.",
    source: "demo",
    persona: {
      type: "highly_interested",
      openness: 0.94,
      enthusiasm: 0.92,
      availability: "30 days",
      compensationSensitivity: "medium",
      likelyObjections: ["Would like to understand platform roadmap and engineering ownership."],
    },
  },
  {
    id: "demo-rohan-iyer",
    name: "Rohan Iyer",
    email: "rohan.iyer@example.com",
    phone: "+91 98765 10102",
    location: "Pune, India",
    currentTitle: "Staff Backend Engineer",
    currentCompany: "CloudWorks",
    yearsExperience: 10,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "GCP", "LLM APIs", "RAG", "Observability", "Distributed Systems"],
    projects: ["Designed a high-throughput AI document processing backend", "Scaled PostgreSQL-backed APIs to 40M requests per day"],
    summary: "Excellent backend and GenAI match, currently happy but open to unusually strong platform roles.",
    source: "demo",
    persona: {
      type: "passive",
      openness: 0.64,
      enthusiasm: 0.58,
      availability: "60 days",
      compensationSensitivity: "medium",
      likelyObjections: ["Needs clarity on compensation, team quality, and scope."],
    },
  },
  {
    id: "demo-nisha-kapoor",
    name: "Nisha Kapoor",
    email: "nisha.kapoor@example.com",
    phone: "+91 98765 10103",
    location: "Delhi NCR, India",
    currentTitle: "Lead Backend Engineer",
    currentCompany: "FinGrid",
    yearsExperience: 9,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "Azure", "LLM APIs", "Microservices", "System Design"],
    projects: ["Introduced AI-assisted underwriting APIs", "Rebuilt a risk scoring service on FastAPI and PostgreSQL"],
    summary: "Strong backend leader with practical LLM API exposure and fintech reliability background.",
    source: "demo",
    persona: {
      type: "compensation_sensitive",
      openness: 0.78,
      enthusiasm: 0.72,
      availability: "45 days",
      compensationSensitivity: "high",
      likelyObjections: ["Wants compensation range early.", "Prefers strong title alignment."],
    },
  },
  {
    id: "demo-arjun-rao",
    name: "Arjun Rao",
    email: "arjun.rao@example.com",
    phone: "+91 98765 10104",
    location: "Goa, India",
    currentTitle: "Senior Platform Engineer",
    currentCompany: "RemoteBase",
    yearsExperience: 7,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "AWS", "Terraform", "RAG", "Vector Databases"],
    projects: ["Built remote-first developer platform APIs", "Shipped RAG ingestion pipelines for customer support copilots"],
    summary: "High-quality remote-first platform engineer with GenAI implementation experience.",
    source: "demo",
    persona: {
      type: "remote_only",
      openness: 0.84,
      enthusiasm: 0.76,
      availability: "30 days",
      compensationSensitivity: "medium",
      likelyObjections: ["Only considering fully remote roles."],
    },
  },
  {
    id: "demo-priya-shah",
    name: "Priya Shah",
    email: "priya.shah@example.com",
    phone: "+91 98765 10105",
    location: "Mumbai, India",
    currentTitle: "Senior Backend Developer",
    currentCompany: "PayNest",
    yearsExperience: 8,
    skills: ["Python", "Django", "PostgreSQL", "Docker", "AWS", "Redis", "Microservices", "System Design"],
    projects: ["Owned payment ledger services", "Improved PostgreSQL query latency by 45 percent"],
    summary: "Excellent backend engineer with no hands-on GenAI production work yet.",
    source: "demo",
    persona: {
      type: "highly_interested",
      openness: 0.89,
      enthusiasm: 0.86,
      availability: "45 days",
      compensationSensitivity: "low",
      likelyObjections: ["Would need ramp-up support on RAG and LLM APIs."],
    },
  },
  {
    id: "demo-kabir-sethi",
    name: "Kabir Sethi",
    email: "kabir.sethi@example.com",
    phone: "+91 98765 10106",
    location: "Bengaluru, India",
    currentTitle: "GenAI Engineer",
    currentCompany: "PromptOps",
    yearsExperience: 4,
    skills: ["Python", "LangChain", "LLM APIs", "RAG", "Vector Databases", "Prompt Engineering", "FastAPI", "Pinecone"],
    projects: ["Built RAG prototypes for sales enablement", "Created evaluation harnesses for LLM prompts"],
    summary: "Strong GenAI builder, but backend depth and production ownership are still developing.",
    source: "demo",
    persona: {
      type: "available_immediately",
      openness: 0.96,
      enthusiasm: 0.94,
      availability: "Immediate",
      compensationSensitivity: "medium",
      likelyObjections: ["Needs senior backend mentorship."],
    },
  },
  {
    id: "demo-meera-joshi",
    name: "Meera Joshi",
    email: "meera.joshi@example.com",
    phone: "+91 98765 10107",
    location: "Hyderabad, India",
    currentTitle: "Backend Engineer",
    currentCompany: "EduSpark",
    yearsExperience: 3,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "OpenAI API", "TypeScript"],
    projects: ["Built a student feedback assistant", "Maintained course APIs"],
    summary: "Promising and enthusiastic engineer, below the seniority bar for a 5+ years role.",
    source: "demo",
    persona: {
      type: "highly_interested",
      openness: 0.98,
      enthusiasm: 0.95,
      availability: "15 days",
      compensationSensitivity: "low",
      likelyObjections: ["May need leveling discussion due to years of experience."],
    },
  },
  {
    id: "demo-vikram-das",
    name: "Vikram Das",
    email: "vikram.das@example.com",
    phone: "+65 8123 1108",
    location: "Singapore",
    currentTitle: "Principal Backend Engineer",
    currentCompany: "TradeAxis",
    yearsExperience: 12,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "Kubernetes", "GCP", "Distributed Systems", "LLM APIs"],
    projects: ["Led low-latency trading APIs", "Prototyped internal AI analyst tools"],
    summary: "Very senior backend engineer with relevant AI exposure, but location and compensation may not fit an India remote role.",
    source: "demo",
    persona: {
      type: "passive",
      openness: 0.52,
      enthusiasm: 0.48,
      availability: "90 days",
      compensationSensitivity: "high",
      likelyObjections: ["Location and compensation expectations may be difficult."],
    },
  },
  {
    id: "demo-sneha-nair",
    name: "Sneha Nair",
    email: "sneha.nair@example.com",
    phone: "+91 98765 10109",
    location: "Kochi, India",
    currentTitle: "Senior Database Engineer",
    currentCompany: "DataLattice",
    yearsExperience: 9,
    skills: ["PostgreSQL", "pgvector", "SQL", "Python", "Performance Tuning", "Data Modeling", "Docker"],
    projects: ["Optimized vector search indexes for a support AI prototype", "Managed mission-critical PostgreSQL clusters"],
    summary: "Deep PostgreSQL and vector database profile, lighter on API service ownership.",
    source: "demo",
    persona: {
      type: "compensation_sensitive",
      openness: 0.74,
      enthusiasm: 0.67,
      availability: "60 days",
      compensationSensitivity: "high",
      likelyObjections: ["Needs clarity on backend scope versus database specialist work."],
    },
  },
  {
    id: "demo-omar-farooqui",
    name: "Omar Farooqui",
    email: "omar.farooqui@example.com",
    phone: "+91 98765 10110",
    location: "Chennai, India",
    currentTitle: "Cloud Platform Engineer",
    currentCompany: "InfraLoop",
    yearsExperience: 8,
    skills: ["AWS", "Kubernetes", "Docker", "Terraform", "Python", "Observability", "Distributed Systems", "PostgreSQL"],
    projects: ["Created internal platform for service templates", "Reduced incident response time with telemetry automation"],
    summary: "Strong cloud and platform candidate with modest GenAI and FastAPI exposure.",
    source: "demo",
    persona: {
      type: "passive",
      openness: 0.61,
      enthusiasm: 0.56,
      availability: "60 days",
      compensationSensitivity: "medium",
      likelyObjections: ["May prefer infrastructure-heavy scope."],
    },
  },
  {
    id: "demo-divya-ramesh",
    name: "Divya Ramesh",
    email: "divya.ramesh@example.com",
    phone: "+91 98765 10111",
    location: "Bengaluru, India",
    currentTitle: "Backend Engineer",
    currentCompany: "Previous Applicant",
    yearsExperience: 6,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "AWS", "Celery", "REST APIs"],
    projects: ["Applied previously for platform team", "Built event-driven onboarding services"],
    summary: "Previous applicant with solid backend skills and renewed interest in AI platform work.",
    source: "demo",
    persona: {
      type: "highly_interested",
      openness: 0.91,
      enthusiasm: 0.88,
      availability: "30 days",
      compensationSensitivity: "medium",
      likelyObjections: ["Will ask how this role differs from prior opening."],
    },
  },
  {
    id: "demo-rahul-banerjee",
    name: "Rahul Banerjee",
    email: "rahul.banerjee@example.com",
    phone: "+91 98765 10112",
    location: "Kolkata, India",
    currentTitle: "Senior Software Engineer",
    currentCompany: "Referred by Anika",
    yearsExperience: 7,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "Azure", "LLM APIs", "RAG", "Kafka"],
    projects: ["Referral candidate for AI workflow backend", "Built async ingestion APIs for enterprise data"],
    summary: "Referral candidate with strong API, data ingestion, and LLM workflow experience.",
    source: "demo",
    persona: {
      type: "available_immediately",
      openness: 0.93,
      enthusiasm: 0.9,
      availability: "Immediate",
      compensationSensitivity: "low",
      likelyObjections: ["Wants quick process due to active search."],
    },
  },
  {
    id: "demo-sanjay-kulkarni",
    name: "Sanjay Kulkarni",
    email: "sanjay.kulkarni@example.com",
    phone: "+91 98765 10113",
    location: "Pune, India",
    currentTitle: "Engineering Lead",
    currentCompany: "EnterpriseSoft",
    yearsExperience: 11,
    skills: ["Python", "Java", "PostgreSQL", "Docker", "AWS", "Distributed Systems", "Architecture", "Team Leadership"],
    projects: ["Led enterprise workflow modernization", "Designed multi-region backend services"],
    summary: "Senior enterprise backend lead, long notice period and limited GenAI depth.",
    source: "demo",
    persona: {
      type: "passive",
      openness: 0.59,
      enthusiasm: 0.52,
      availability: "90 days",
      compensationSensitivity: "medium",
      likelyObjections: ["Long notice period.", "May expect people leadership scope."],
    },
  },
  {
    id: "demo-tara-mukherjee",
    name: "Tara Mukherjee",
    email: "tara.mukherjee@example.com",
    phone: "+91 98765 10114",
    location: "Noida, India",
    currentTitle: "Backend Platform Engineer",
    currentCompany: "Searchly",
    yearsExperience: 6,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "GCP", "Elasticsearch", "Vector Search", "LLM APIs"],
    projects: ["Available after startup layoff", "Built semantic search APIs for knowledge products"],
    summary: "Available immediately with strong search, backend, and LLM integration experience.",
    source: "demo",
    persona: {
      type: "available_immediately",
      openness: 0.97,
      enthusiasm: 0.93,
      availability: "Immediate",
      compensationSensitivity: "medium",
      likelyObjections: ["Needs fast recruiter follow-up."],
    },
  },
  {
    id: "demo-ishaan-gupta",
    name: "Ishaan Gupta",
    email: "ishaan.gupta@example.com",
    phone: "+91 98765 10115",
    location: "Gurugram, India",
    currentTitle: "Senior AI Platform Engineer",
    currentCompany: "ScaleMind",
    yearsExperience: 8,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "Kubernetes", "LLM APIs", "RAG", "Vector Databases", "Distributed Systems"],
    projects: ["Built production LLM evaluation and RAG services", "Published internal libraries for AI platform teams"],
    summary: "Very high skill match but currently not seeking a move.",
    source: "demo",
    persona: {
      type: "not_interested",
      openness: 0.18,
      enthusiasm: 0.12,
      availability: "Not available",
      compensationSensitivity: "low",
      likelyObjections: ["Happy in current role.", "Not open this quarter."],
    },
  },
  {
    id: "demo-lavanya-krishnan",
    name: "Lavanya Krishnan",
    email: "lavanya.krishnan@example.com",
    phone: "+91 98765 10116",
    location: "Coimbatore, India",
    currentTitle: "Software Engineer II",
    currentCompany: "HealthBridge",
    yearsExperience: 5,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "OpenAI API", "Healthcare APIs"],
    projects: ["Built patient summarization workflow", "Maintained API platform for clinics"],
    summary: "Medium skill match with unusually high motivation to work on GenAI platforms.",
    source: "demo",
    persona: {
      type: "highly_interested",
      openness: 0.96,
      enthusiasm: 0.97,
      availability: "30 days",
      compensationSensitivity: "low",
      likelyObjections: ["Needs validation on distributed systems depth."],
    },
  },
  {
    id: "demo-devansh-trivedi",
    name: "Devansh Trivedi",
    email: "devansh.trivedi@example.com",
    phone: "+91 98765 10117",
    location: "Ahmedabad, India",
    currentTitle: "Open Source Backend Engineer",
    currentCompany: "Independent",
    yearsExperience: 7,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "TypeScript", "LLM APIs", "RAG", "Open Source"],
    projects: ["Maintainer of a FastAPI RAG starter with 4k GitHub stars", "Contributed pgvector examples and evaluation scripts"],
    summary: "Strong open-source signal and hands-on GenAI backend projects.",
    source: "demo",
    persona: {
      type: "remote_only",
      openness: 0.82,
      enthusiasm: 0.79,
      availability: "45 days",
      compensationSensitivity: "medium",
      likelyObjections: ["Needs remote flexibility and open-source time."],
    },
  },
  {
    id: "demo-mohit-verma",
    name: "Mohit Verma",
    email: "mohit.verma@example.com",
    phone: "+91 98765 10118",
    location: "Bengaluru, India",
    currentTitle: "Senior Software Engineer",
    currentCompany: "GlobalEnterprise",
    yearsExperience: 9,
    skills: ["Java", "Python", "PostgreSQL", "Docker", "Kubernetes", "AWS", "Distributed Systems", "Compliance"],
    projects: ["Built enterprise integrations with strict audit controls", "Migrated monolith modules to platform services"],
    summary: "Enterprise-grade engineering background with reliable delivery, but minimal direct RAG exposure.",
    source: "demo",
    persona: {
      type: "passive",
      openness: 0.66,
      enthusiasm: 0.57,
      availability: "60 days",
      compensationSensitivity: "medium",
      likelyObjections: ["Wants mature processes and stable roadmap."],
    },
  },
  {
    id: "demo-zoya-khan",
    name: "Zoya Khan",
    email: "zoya.khan@example.com",
    phone: "+91 98765 10119",
    location: "Jaipur, India",
    currentTitle: "Founding Backend Engineer",
    currentCompany: "TinyPilot AI",
    yearsExperience: 6,
    skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "AWS", "LLM APIs", "LangChain", "RAG", "Product Engineering"],
    projects: ["Built GenAI assistant from zero to first 20 customers", "Owned auth, billing, and AI workflow APIs"],
    summary: "Startup operator with strong end-to-end ownership and relevant GenAI backend delivery.",
    source: "demo",
    persona: {
      type: "compensation_sensitive",
      openness: 0.81,
      enthusiasm: 0.78,
      availability: "30 days",
      compensationSensitivity: "high",
      likelyObjections: ["Will ask about equity, autonomy, and compensation range."],
    },
  },
  {
    id: "demo-aditya-sen",
    name: "Aditya Sen",
    email: "aditya.sen@example.com",
    phone: "+91 98765 10120",
    location: "Bengaluru, India",
    currentTitle: "Data Scientist",
    currentCompany: "InsightLabs",
    yearsExperience: 7,
    skills: ["Python", "Machine Learning", "Pandas", "Jupyter", "Prompt Engineering", "LLM APIs", "Model Evaluation"],
    projects: ["Built churn models and prompt experiments", "Analyzed AI support quality"],
    summary: "Smart AI-adjacent candidate, but profile is data science rather than backend platform engineering.",
    source: "demo",
    persona: {
      type: "highly_interested",
      openness: 0.9,
      enthusiasm: 0.88,
      availability: "30 days",
      compensationSensitivity: "medium",
      likelyObjections: ["Role may not match backend engineering expectations."],
    },
  },
];
